version: '3.8'

services:
  app:
  #  image: 'demo_springboot-1.0.0:latest'
    build:
      context: .
    container_name: app
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - db
  #  environment:
  #    - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/jobportal
  #    - SPRING_DATASOURCE_USERNAME=postgres
  #    - SPRING_DATASOURCE_PASSWORD=Kather@123
  #    - SPRING_JPA_HIBERNATE_DDL_AUTO=update
          
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: Kather@123
      - POSTGRES_DB: jobportal